### ISSUE TITLE
PLACEHOLDER Generated in Observable Pattern Prevents Creating Stix2 Object

### ISSUE THREAD

**Issue by tigerkatz** [oasis-open/cti-stix-elevator#116]
When converting a package with the below observable indicator (some data has been obfuscated...hence xxxx):

```
<indicator:Observable id="ctap:Observable-5e5adadf-ae00-4e9f-a73d-123c9bf35680">
<cybox:Observable_Composition operator="OR">
<cybox:Observable idref="xxxx:Observable-83aa2840-e0df-4369-b9ad-4ac81b58cb80">
</cybox:Observable>
<cybox:Observable id="xxxx:Observable-82042a5f-6c55-4464-a83c-1cf8d6a058cd">
<cybox:Object id="xxxx:URI-2cb4a358-76cc-4ff3-9282-e58b6ab87569">
<cybox:Properties xsi:type="URIObj:URIObjectType" type="URL">
<URIObj:Value>120.204.0.149/mmtls/00004d8d</URIObj:Value>
</cybox:Properties>
</cybox:Object>
</cybox:Observable>
</cybox:Observable_Composition>
</indicator:Observable>
```

A "PLACEHOLDER" value is inserted in the pattern for the Observable idref. Resulting in:

```
 {
            "created": "2018-07-10T22:44:04.768Z",
            "id": "indicator--d465854d-e99e-4685-baa5-03f1d3f30f0b",
            "kill_chain_phases": [
                {
                    "kill_chain_name": "lockheed-martin-cyber-kill-chain",
                    "phase_name": "delivery"
                }
            ],
            "labels": [
                "unknown"
            ],
            "modified": "2018-07-10T22:44:04.768Z",
            "pattern": "[PLACEHOLDER:xxxx:Observable-83aa2840-e0df-4369-b9ad-4ac81b58cb80] OR [url:value = '120.204.0.149/mmtls/00004d8d']",
            "type": "indicator",
            "valid_from": "2018-07-10T22:44:04.768967Z"
        }
```

This object can not be used to instantiate a stix2 object because of PLACEHOLDER.

**Comment by gtback** [comment]
Thanks, @tigerkatz .

This is done because we don't want to silently drop the `Observable-83aa2840` part of the composition, which could cause the meaning of the indicator pattern to change. We decided that by default this should create a "loud" error (by creating invalid STIX 2) rather than a warning that may be ignored. I think there are options that would cause the elevator to just drop the entire indicator rather than emitting an invalid one. @rpiazza do you remember how to do this?

Since that Observable is using an idref, is the full (non-`ref`-ed) Observable available in the same document? The elevator makes some effort to resolve these references, but due to the infinitely-nestable nature of Indicators and Observables, we don't claim to be able to find it 100% of the time.

**Comment by rpiazza** [comment]
Hi @tigerkatz,

I'm not sure what @gtback had in mind, but there is no option to "drop" observables with unresolved PLACEHOLDERs. Although as he said, the problem seems to be the unavailability of the ref-ed Observable.  Is that Observable in the same package?  If so, is it possible for you to send that file so we can debug the problem?

**Comment by gtback** [comment]
@rpiazza, I was thinking there was something in policies that would ensure we didn't emit invalid STIX, but I realize now that's on an entire-file basis, not per-object.

**Comment by rpiazza** [comment]
Hi @tigerkatz,

Was the problem that the observable id that was referenced wasn't available?  If not, can you send the full example?

**Comment by tigerkatz** [comment]
Hi @gtback,

Thank you for reaching out. The problem was that the referenced observable
was not available within the same package, but was in the database. We
implemented a method to "dereference" all idrefs in the package that did
not have the corresponding definitions in the same package, by fetching
them separately from the database, and then doing some xml surgery to put
them back in.  This is done outside of the scope of elevator.

**Comment by tigerkatz** [comment]
Sorry, I meant to say Hi @rpiazza. I think the question is still open, as
to wether or not the elevator should create invalid STIX, if there is just
an idref for an observable that refers to a definition outside the package.

**Comment by rpiazza** [comment]
@tigerkatz,
As I mentioned in #118, you can look into the 'policy' option, which will prevent the generation of invalid STIX by not producing a result if a warning message was generated.  

I'm going to close this for now.  Please reopen it if you have more to discuss.
