### ISSUE TITLE
Issue warning and return sentinel value (not None) for invalid Pattern condition values

### ISSUE THREAD

**Issue by tigerkatz** [oasis-open/cti-stix-elevator#117]
We are processing a large amount of stix1 xml data, some of which has tags with the attribute condition='equals'. When this value is passed to convert_pattern.py condition_check, this returns None due to case sensitivity and thus generates an invalid pattern. 

Input
`<DomainNameObj:Value condition="equals">authorweb.healthstream.com</DomainNameObj:Value>`

Output:
`"pattern": "[domain-name:value None 'authorweb.healthstream.com']`

Can the conditional logic in the method not be case sensitive, and can it return something other than None if a match cannot be achieved?

**Comment by rpiazza** [comment]
I see your point - especially that it returns 'None'.  Certainly "equals" should be acceptable - with an warning message.  However, I'm not sure I want to accept "greaterthanorequal" or even worse "greaterThanorEqual".  @gtback, any thoughts?

Thanks for your interest, @tigerkatz, in making the elevator better!

**Comment by tlhampton13** [comment]
Returning "=" with a warning for the case condition="greaterthanequal" would not be good.  I would like the check to be case insensitive because the STIX 1 libraries are dealing with this lower case version, no problem, and I have 24 million packages of data done this way.

Perhaps if case sensitivity is important to for some, a switch would be useful.

**Comment by tigerkatz** [comment]
I see what your saying. I guess if the logic is case insensitive, something
like 'greaterThanorEqual' would not matter, but would not look pretty.
"equals" seems to be a reasonable thing for a human to do.

**Comment by gtback** [comment]
To be clear, `condition="equals"` is **not valid STIX 1**. The fact that python-stix handles the lower case "equals" is a result of the limited validation the library does. Even `condition="not-a-valid-condition"` is accepted.

In the case of `equals`, it's pretty obvious what the intended value is, but as this conversation suggests, it's a slippery slope. We could do a case-insensitive comparison by calling `lower` on the value, but I'm not sure we want to do that.

The [`convert_condition() function`](https://github.com/oasis-open/cti-stix-elevator/blob/1a3d874b6b8e483b84b4027cabef596e84a3da31/stix2elevator/convert_pattern.py#L387) could likely be improved by (1) printing a warning at the end of the function and (2) returning a sentinel value like `INVALID-CONDITION`, rather than the current behavior of implicitly returning `None`. In other places in the elevator, rather than rejecting the pattern altogether, the elevator produces a mostly-complete pattern that is hopefully easy to correct later, rather than rejecting the entire indicator. I agree that returning `=` is dangerous and we should avoid that 😀 .

@tlhampton13 , I'm sympathetic to having to deal with 24 million invalid STIX packages, but in this case, would it be feasible to do a global replace of `condition="equals"` with `condition="Equals"`, and similar for any other lower-case condition values? That string should be specific enough that there won't be false positives. The [stix-validator](https://stix-validator.readthedocs.io/en/stable/index.html) is also useful for catching these types of errors: 

```
"<string>:28:0:ERROR:SCHEMASV:SCHEMAV_CVC_ENUMERATION_VALID: Element 
'{http://cybox.mitre.org/objects#AddressObject-2}Address_Value', attribute 'condition': [facet 
'enumeration'] The value 'not-a-valid-condition' is not an element of the set {'Equals', 
'DoesNotEqual', 'Contains', 'DoesNotContain', 'StartsWith', 'EndsWith', 'GreaterThan', 
'GreaterThanOrEqual', 'LessThan', 'LessThanOrEqual', 'InclusiveBetween', 'ExclusiveBetween', 
'FitsPattern', 'BitwiseAnd', 'BitwiseOr', 'BitwiseXor'}."
```

**Comment by rpiazza** [comment]
The compromise fix is as follows:
- 'equals' is allowed, but you also get a warning message
- No condition assumes '=', with a warning message
- any invalid values, included case-sensitive ones, will return "INVALID-CONDITION', with a warning message

Fix should be available soon - on github only

**Comment by tlhampton13** [comment]
@gtback no argument, condition="greaterthanequal" is **NOT valid STIX 1**, but It is also **NOT ambiguous**. Converting the word "greaterthanequal" regardless of case to ">=" will always result in the desired STIX 2 result.

**Comment by gtback** [comment]
@rpiazza Your PR handles case-insensitive "equals". Should we allow case-insensitive values for other conditions (with a warning)? It makes the code a bit more verbose, but we could probably do it in a more general way.

**Comment by rpiazza** [comment]
@gtback - my compromise was to accept only 'equals'.  The elevator makes an attempt to "fix" some invalid STIX 1.x content, but that is a slippery slope.  On the other hand, if you feel this is another situation where it should, I can make further changes.

**Comment by gtback** [comment]
@tlhampton13 you have a good point that it's not ambiguous. Do you have actual STIX content that contains `condition="greaterhtanorequal"` or other lower-case conditions other than "equals"? Even thought it's a slippery slope, I'm okay with adding those as long as people actually need them, rather than just adding fixes for invalid content because we thought of the scenario.

**Comment by tlhampton13** [comment]
@gtback unfortunately yes, i have a lot of STIX content that i'm pulling from a TAXII 1 server that is looking this way.  It's not limited to just one of the conditions.

Here is a proposal for how this might be handled generically.

1)  Create case-insensitive enums for the STIX 1 enums (uses a case insensitive str class)

```python
from istr import IStr

def enum(**named_values):
    return type('Enum', (), named_values)

ConditionTypeEnum = enum(
    EQUALS=IStr('Equals'),
    DOES_NOT_EQUAL=IStr('DoesNotEqual'),
    CONTAINS=IStr('Contains')
    # ...
)
```

2) Case-insensitive str class.  Notice that except for comparison & lookups it otherwise behaves as case-sensitive str.

```python
class IStr(str):
    """
    Case insensitive string class.
    Behaves just like str, except that all comparisons and lookups
    are case insensitive.
    """
    def __init__(self, *args):
        str.__init__(self)
        self._lowered = str.lower(self)

    def __repr__(self):
        return '%s(%s)' % (type(self).__name__, str.__repr__(self))

    def __hash__(self):
        return hash(self._lowered)

    def lower(self):
        return self._lowered
    
    
def _make_case_insensitive(name):
    """ wrap one method of str into an IStr one, case-insensitive """
    try:
        str_meth = getattr(str, name)

        def x(self, other, *args):
            """
            try lowercasing 'other', which is typically a string, but
            be prepared to use it as-is if lowering gives problems,
            since strings CAN be correctly compared with non-strings.
            """
            try:
                other = other.lower()
            except (TypeError, AttributeError, ValueError):
                pass
            return str_meth(self._lowered, other, *args)
        # in Python 2.4, only, add the statement: x.func_name = name
        setattr(IStr, name, x)
    except AttributeError:
        pass


# apply the _make_case_insensitive function to specified methods 
for n in 'eq lt le gt ge ne contains cmp'.split():
    _make_case_insensitive('__%s__' % n)
for n in 'count endswith find index rfind rindex startswith'.split():
    _make_case_insensitive(n)
# note that we don't modify methods 'replace', 'split', 'strip', ...
# of course, you can add modifications to them, too, if you prefer that.
del _make_case_insensitive    # remove helper function, not needed any more
```

3) works nicely, and may even make your code cleaner by removing hard-coded strings :)

```python
from enums import *

if 'DoesNotEqual' == ConditionTypeEnum.DOES_NOT_EQUAL:
    print("equal")
if 'doesnotequal' == ConditionTypeEnum.DOES_NOT_EQUAL:
    print("equal")
if 'DOESNOTEQUAL' == ConditionTypeEnum.DOES_NOT_EQUAL:
    print("equal")
if 'DoEsNoTeQuAl' == ConditionTypeEnum.DOES_NOT_EQUAL:
    print("equal")
if 'ShouldNotBeEqual' == ConditionTypeEnum.DOES_NOT_EQUAL:
    print("equal")
else:
    print("not equal")
```

**Comment by tlhampton13** [comment]
@gtback @rpiazza 
BTW, we really appreciate the work your team is doing on the elevator.  We have had very good success using it so far.

**Comment by gtback** [comment]
Thanks for the kind words, @tlhampton13 . 

I was thinking something along the lines of:
```python
CONDITION_OPERATOR_MAP = {
    'Equals': "=",
    'GreaterThanOrEqual': ">=",
    ...
}

for cond, op in CONDITION_OPERATOR_MAP.items():
    if cond.lower() == condition.lower():
        if cond != condition:
            <print warning message about case not matching>
        return op
<print warning about unexpected operator>
return None/Placeholder
```

An alternative:
```python

CONDITION_OPERATOR_MAP = {
    'equals': ('Equals', "="),
    'greaterthanorequal': ('GreaterThanOrEqual', ">="),
    ...
}

try:
    cond, op = CONDITION_OPERATOR_MAP[condition.lower()]
except KeyError:
    <print warning about unexpected operator>
    return None/Placeholder
else:
    if cond != condition:
        <print warning message about case not matching>
    return op
```

In either case, the behavior of treating a missing condition as "=" should be handled first.
But there's a thousand ways to address this 😁.

**Comment by tlhampton13** [comment]
Agreed...many way's to achieve success :) 

I was thinking you might consider doing this for all the Enum values, not just for the condition operator.  But, that is the only one I'm currently aware of that is causing us a problem.

**Comment by rpiazza** [comment]
@gtback: your first solution was the one I was thinking of.... :-)

I will make that change.
