### ISSUE TITLE
Could not resolve Marking Structure

### ISSUE THREAD

**Issue by cyberfox1** [oasis-open/cti-stix-elevator#121]
It seems the elevator has issues resolving a Marking Structure to it's definition using idref.

E.g. if I have this header in the document:

    <stix:STIX_Header>
        <stix:Handling>
            <marking:Marking>
                <marking:Marking_Structure id="FOOBAR:markingstructure-c0d0976c-76a1-4cf2-accd-19632991ac3f" xsi:type='TOUMarking:TermsOfUseMarkingStructureType'>
                    <TOUMarking:Terms_Of_Use>Classification: PROTECTED</TOUMarking:Terms_Of_Use>
                </marking:Marking_Structure>
            </marking:Marking>
        </stix:Handling>
    </stix:STIX_Header>

And then an idref backreference later on like:

            <indicator:Handling>
                <marking:Marking>
                    <marking:Controlled_Structure>../../../descendant-or-self::node() | ../../../descendant-or-self::node()/@*</marking:Controlled_Structure>
                    <marking:Marking_Structure idref="FOOBAR:markingstructure-c0d0976c-76a1-4cf2-accd-19632991ac3f"/>
                </marking:Marking>
            </indicator:Handling>

The elevator blows up with:

      File "/data/dev/cti-api/venv3/lib/python3.6/site-packages/stix2elevator/__init__.py", line 115, in elevate_string
        get_option_value("default_timestamp")),
      File "/data/dev/cti-api/venv3/lib/python3.6/site-packages/stix2elevator/convert_stix.py", line 1706, in convert_package
        bundle_instance["objects"].extend(convert_marking_specification(marking_specification, bundle_instance, package_created_by_ref, parent_timestamp))
      File "/data/dev/cti-api/venv3/lib/python3.6/site-packages/stix2elevator/convert_stix.py", line 258, in convert_marking_specification
        raise(NameError("Could not resolve Marking Structure %s" % identifying_info(mark_spec)))
    NameError: Could not resolve Marking Structure  with idref FOOBAR:markingstructure-c0d0976c-76a1-4cf2-accd-19632991ac3f
    
Note we came up with a fix that works for us and might be useful:

stix2elevator/convert_stix.py (stix2-elevator==1.1.3)

    247a248,250
    >             elif (hasattr(mark_spec, "idref") and mark_spec.idref):
    >                 marking_definition_instance["id"] = generate_stix20_id("marking-definition", mark_spec.idref)
    >                 return_obj.append(marking_definition_instance)
    289c292,298
    <                 bundle_instance["objects"].extend(stix20_markings)
    ---
    >                 new_ms_list = []
    >                 for ms in stix20_markings:
    >                     if 'definition' in ms:
    >                         new_ms_list.append(ms)
    >                 if new_ms_list:
    >                     bundle_instance["objects"].extend(new_ms_list)
    >                 
    1701c1710,1716
    <             bundle_instance["objects"].extend(convert_marking_specification(marking_specification, bundle_instance, package_created_by_ref, parent_timestamp))
    ---
    >             ms_list = convert_marking_specification(marking_specification, bundle_instance, package_created_by_ref, parent_timestamp)
    >             new_ms_list = []
    >             for ms in ms_list:
    >                 if 'definition' in ms:
    >                     new_ms_list.append(ms)
    >             if new_ms_list:
    >                 bundle_instance["objects"].extend(new_ms_list)

**Comment by emmanvg** [comment]
@cyberfox1, thanks for you suggestion. I decided to take a slightly different approach but will still achieve the same result. MarkingStructure objects with idref are not really useful since they don't contain the definitions. Hence, I decided to add a message for those and another message when markings are created successfully. Thus, when you run the tool with the proposed changes you should see a message saying "Could not resolve marking... [id]" and another one in the future with "Created Marking Structure for... [id]" when the definition is found. It will also reuse the `id` if present in the marking structure. Hopefully this will address your issue.

**Comment by cyberfox1** [comment]
@emmanvg thanks for that, can I just clarify when you say "MarkingStructure objects with idref are not really useful since they don't contain the definitions" - but isn't that the point of idref, to refer to a definition defined elsewhere? I will try and verify if your changes produce an output that works for us.

**Comment by emmanvg** [comment]
> @emmanvg thanks for that, can I just clarify when you say "MarkingStructure objects with idref are not really useful since they don't contain the definitions" - but isn't that the point of idref, to refer to a definition defined elsewhere? I will try and verify if your changes produce an output that works for us.

Indeed, that is the purpose but for the conversion purposes the important piece is the definition in order to have a STIX 2.0 representation. Once we have that, we can establish a mapping anywhere in the document from a STIX1.X marking -> STIX2.0 marking using the approach you deem most appropriate for your use-case (no-id, id/idref).

I think this was not added initially because most of the sample data I saw **did not** have a `Marking_Structure` with `id`, thus requiring a more complex approach. Either way, nice to hear the changes work 👍
