### ISSUE TITLE
Empty report causes error: 'NoneType' object has no attribute 'information_source'

### ISSUE THREAD

**Issue by cyberfox1** [oasis-open/cti-stix-elevator#129]
Given a stix package with the rough following structure:

    <stix:STIX_Package 
    ...
    >
        <stix:Indicators>
           ...
        </stix:Indicators>
        <stix:Reports>
            <stix:Report timestamp="2018-09-12T00:00:16.906Z"/>
        </stix:Reports>
    </stix:STIX_Package>

A document based on above structure passes stix1 validation, but the elevator blows up with:

    python3.6/site-packages/stix2elevator/convert_stix.py", line 1227, in convert_report
        report_created_by_def = process_information_source(report.header.information_source, 
    report_instance,
    AttributeError: 'NoneType' object has no attribute 'information_source'

**Comment by rpiazza** [comment]
Hi @cyberfox1,

Yes, we should check to see if the report has a header before we try to access header attributes.

However, I wonder what the purpose of the report object you created is, since it has no objects in it.  Objects in the package are not necessarily in the report, they must be explicitly included.  A package can contain more that one report.

**Comment by cyberfox1** [comment]
> However, I wonder what the purpose of the report object

Thanks @rpiazza...as do I.
