### ISSUE TITLE
CVE ID Format not translated correctly

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix-elevator#133]
CVE ID ID formate is different between STIX 1.1 and STIX 2.x. In STIX 1.1, CVE ID format is "CVE-\d\d\d\d-\d+" while STIX 2.X the format is "^CVE-\\d{4}-(0\\d{3}|[1-9]\\d{3,})$".  In STIX 2.X, the CVE ID has 4 or more number in the second part of the CVE ID. Stix Elevator doesn't properly translate CVE ID in STIX 1.1 to CVE ID in STIX 2.x.

Here is an example that is always failing. 

```
<stix:Exploit_Targets>
   <stixCommon:Exploit_Target id="et-08-1" timestamp="9999-12-31T00:00:00Z" xsi:type="et:ExploitTargetType">
			<et:Vulnerability>
				<et:CVE_ID>CVE-0008-0</et:CVE_ID>
				<et:OSVDB_ID>1</et:OSVDB_ID>
			</et:Vulnerability>
			<et:Vulnerability>
				<et:CVE_ID>CVE-0008-1</et:CVE_ID>
				<et:OSVDB_ID>1</et:OSVDB_ID>
			</et:Vulnerability>
			<et:Potential_COAs>
				<et:Potential_COA>
					<stixCommon:Course_Of_Action idref="coa-08-1" timestamp="9999-12-31T00:00:00Z"></stixCommon:Course_Of_Action>
				</et:Potential_COA>
			</et:Potential_COAs>
		</stixCommon:Exploit_Target>
	</stix:Exploit_Targets>
```

**Comment by rpiazza** [comment]
Hi @hanymorcos.  Another issue that fell thru the cracks because of the holidays. :-(

Thanks for your issue!

If you look at https://cve.mitre.org/cve/identifiers/syntaxchange.html, you will see that the CVE IDs in your example were never actually legal - since the first 4 digits should represent a year, and there needs to be 4 digits in the second part (with leading 0s as necessary).

The old regular expression was underspecified, so it allowed your CVE IDs.  The new regular expression is better, but still doesn't enforce that the year for the first 4 digits.

I'm not sure if the example you posted was for testing, because it seems like no CVE with that ID ever could have existed.

At any rate, I think you probably need to update your examples to have legal CVE IDs as described in that website.  I will close this issue - feel free to open it again if you have further comments.
