### ISSUE TITLE
consistency in file hash conversion

### ISSUE THREAD

**Issue by HBadger0017** [oasis-open/cti-stix-elevator#160]
Howdy,
I'm converting STIX 1.1.1 to STIX2 and I have noticed a consistency issue.

I have a STIX1 doc with file hash IoCs in them (e.g. MD5, SHA-1, SHA-256, and ssdeep).  

My STIX1 input is as follows:
...
<FileObj:Hashes>
	<cyboxCommon:Hash>
		<cyboxCommon:Type condition="Equals" xsi:type="cyboxVocabs:HashNameVocab-1.0">MD5</cyboxCommon:Type>
		<cyboxCommon:Simple_Hash_Value condition="Equals">Redacted</cyboxCommon:Simple_Hash_Value>
	</cyboxCommon:Hash>
	<cyboxCommon:Hash>
		<cyboxCommon:Type condition="Equals" xsi:type="cyboxVocabs:HashNameVocab-1.0">SHA1</cyboxCommon:Type>
		<cyboxCommon:Simple_Hash_Value condition="Equals">Redacted</cyboxCommon:Simple_Hash_Value>
	</cyboxCommon:Hash>
	<cyboxCommon:Hash>
		<cyboxCommon:Type condition="Equals" xsi:type="cyboxVocabs:HashNameVocab-1.0">SHA256</cyboxCommon:Type>
		<cyboxCommon:Simple_Hash_Value condition="Equals">Redacted</cyboxCommon:Simple_Hash_Value>
	</cyboxCommon:Hash>
	<cyboxCommon:Hash>
		<cyboxCommon:Type condition="Equals" xsi:type="cyboxVocabs:HashNameVocab-1.0">SSDEEP</cyboxCommon:Type>
		<cyboxCommon:Fuzzy_Hash_Value condition="Equals">Redacted</cyboxCommon:Fuzzy_Hash_Value>
	</cyboxCommon:Hash>
</FileObj:Hashes>
...

When the elevator completes, I get the following output:
file:hashes.MD5
file:hashes.'SHA-1'
file:hashes.'SHA-256'
file:hashes.ssdeep

I'd like to know if there is a tweak I can do to get the STIX2 output to be:
file:hashes.md5
file:hashes.sha1
file:hashes.sha256
file:hashes.ssdeep
...
etc. for the rest of the supported hashes

Or is this an issue?

End result is to be able to parse the output but hash type.

Thanks in advance.

-Matthew KW

**Comment by rpiazza** [comment]
Hi @HBadger0017,

From the xml you sent and the results you show, my assumption is that this is an Observable within an Indicator, acting as a pattern to match against.  

The names of the hashes are listed in the specification, and they must appear in the pattern expression exactly (including lower/upper case) as the appear in the spec for them to be valid in STIX 2.0 (see Part 1, section 6.3).  It could be a little confusing, because if a '_' occurs in an object path component - it must be quoted - which is why you have ``MD5`` and ``'SHA-256'``.

How are you consuming the resultant STIX 2.0?  Any STIX compliant code should handle the hash names as listed in the spec.

**Comment by HBadger0017** [comment]
I am pulling IoCs from STIX2 json to build the intel framework for Zeek.  Got the reference and I'll adjust my code accordingly.  Thanks for the quick response.

-Matthew KW
