### ISSUE TITLE
Handle NOT modifier in Patterns

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-stix-elevator#18]

**Comment by rpiazza** [comment]
Fixed in https://github.com/oasis-open/cti-stix-elevator/commit/5d8193e288f7796ded627fa0b5683825a60dadcf

Ignore the negate attribute for now.  It probably isn't used often (its not used in our test cases), and treating it correctly involves using Demorgan's laws to distribute the NOTs down to the comparison expressions - which is a significant redesign.

**Comment by rpiazza** [comment]
see #27
